#!/bin/ksh

site=$1
ptype=$2

case $ptype in
	posts)
	rqtype="post"
	;;
	pages)
	rqtype="page"
	;;
	*)
	echo "The type argument must be either 'posts' or 'pages'."
	;;
esac

site_url="$site.wordpress.com"
site_dir="../blog/$site.wordpress.com/"

dir_type="$site_dir/$ptype/"

#
# If the site does not exist, we inform the user.
#
if [[ ! -d $site_dir ]]; then
	echo "$site_url does not exist."
	echo "Create it online, and run the 'wpsync' command."
	exit;
fi

ls $dir_type
