#!/bin/ksh

# This script uploads media to wordpress.com It uploads it to the media library
# of a specific blog.  This media library is reflected in the directory
# structure in the blog/ directory. The media library is stored in
# blog/<blogurl>/mlib/.

# When a call to publish is made, an attribute is set at runtime that allows a
# macro-like object to expand into the proper URL or path.

# Argument 1 is the site-name. Argument 2 is the path to the media file. 

site=$1
ptype="mlib"
file=$2


site_url="$site.wordpress.com"
sitepath="../blog/$site_url/"
fpath="../blog/$site_url/$ptype/"
fname=$(basename $2)
if [[ ! -d $sitepath ]]; then
	echo "There is no site '$site_url'"
	echo "Check your spelling"
	echo "If the site actually exists, run the 'wpsync' command"
	exit
fi
if [[ ! -d $fpath ]]; then
	mkdir $fpath
fi
if [[ ! -f $fpath$fname ]]; then
	echo "The media doesn't exist"
	echo "Can't remove file that hasn't been uploaded from the framework."
	exit
fi

meta_data="../blog/$site.wordpress.com/$ptype/$fname.json"
media_id=$(cat $meta_data | json media[0].ID)

rm ../blog/$site.wordpress.com/$ptype/$fname 

curl="curl -s -k"

rest_url="https://public-api.wordpress.com/rest/v1.1/sites/$site_url/media/$media_id/delete/"

tok=$(./wplogin)



$curl --data '' -H "Authorization: Bearer $tok" \
	"$rest_url" > /dev/null
